module.exports = {
  CWD_CHANGED: 'cwd_changed',
  PROGRESS_CHANGED: 'progress_changed',
  PROGRESS_REMOVED: 'progress_removed',
  CONSOLE_LOG_ADDED: 'console_log_added',
  TASK_CHANGED: 'task_changed',
  TASK_LOG_ADDED: 'task_log_added',
  VIEW_ADDED: 'view_added',
  VIEW_REMOVED: 'view_removed',
  VIEW_CHANGED: 'view_changed',
  CLIENT_ADDON_ADDED: 'client_addon_added',
  SHARED_DATA_UPDATED: 'shared_data_updated',
  PLUGIN_ACTION_CALLED: 'plugin_action_called',
  PLUGIN_ACTION_RESOLVED: 'plugin_action_resolved',
  LOCALE_ADDED: 'locale_added',
  SUGGESTION_ADDED: 'suggestion_added',
  SUGGESTION_REMOVED: 'suggestion_removed',
  SUGGESTION_UPDATED: 'suggestion_updated',
  ROUTE_REQUESTED: 'route_requested'
}
